# Generated by Django 4.2.7 on 2025-12-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('citizenship', 'Citizenship Certificate'), ('license', 'Driving License'), ('pan', 'PAN Card'), ('bank_statement', 'Bank Statement'), ('salary_slip', 'Salary Slip'), ('passport_photo', 'Passport Size Photos'), ('tax_clearance', 'Tax Clearance Certificate'), ('passport', 'Passport'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('application', 'document_type')},
        ),
    ]
