# Generated by Django 4.2.7 on 2025-12-28 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='incomplete', max_length=20),
        ),
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('grandfather_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('permanent_address', models.TextField()),
                ('permanent_district', models.CharField(max_length=100)),
                ('permanent_province', models.CharField(max_length=100)),
                ('temporary_address', models.TextField(blank=True, null=True)),
                ('temporary_district', models.CharField(blank=True, max_length=100, null=True)),
                ('temporary_province', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('citizenship_number', models.CharField(max_length=50, unique=True)),
                ('citizenship_issue_date', models.DateField()),
                ('citizenship_issue_district', models.CharField(max_length=100)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('employer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='incomplete', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kyc_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('citizenship_front', 'Citizenship Certificate (Front)'), ('citizenship_back', 'Citizenship Certificate (Back)'), ('license', 'Driving License'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('photo', 'Passport Size Photo'), ('signature', 'Signature')], max_length=30)),
                ('file', models.FileField(upload_to='kyc_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.kycprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_documents',
                'ordering': ['-uploaded_at'],
                'unique_together': {('kyc_profile', 'document_type')},
            },
        ),
    ]
