# Generated by Django 4.2.7 on 2025-12-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_kyc_status_kycprofile_kycdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='abs_status',
            field=models.BooleanField(default=False, verbose_name='Has ABS'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brake_type',
            field=models.CharField(choices=[('disc', 'Disc'), ('drum', 'Drum'), ('both', 'Both Disc')], default='disc', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cbs_status',
            field=models.BooleanField(default=False, verbose_name='Has CBS'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_capacity',
            field=models.IntegerField(blank=True, help_text='Engine capacity in cc', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_tank_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel tank capacity in Liters', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='horsepower',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horsepower in bhp', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mileage in km/l', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='top_speed',
            field=models.IntegerField(blank=True, help_text='Top speed in km/h', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wheel_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
