# Generated by Django 4.2.7 on 2025-12-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vehicle_abs_status_vehicle_brake_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_system',
            field=models.CharField(blank=True, choices=[('fi', 'Fuel Injection (FI)'), ('carburetor', 'Carburetor')], default='fi', max_length=50, null=True),
        ),
    ]
